kind: Deployment
apiVersion: apps/v1
metadata:
  name: logging-app3-deployment
  namespace: logging
spec:
  selector:
    matchLabels:
      app: logging-app3
  replicas: 1
  template:
    metadata:
      labels:
        app: logging-app3
    spec:
      containers:
        - name: logging-app3
          ports:
            - name: external-http
              containerPort: 8082
              protocol: TCP
          imagePullPolicy: Always
          image: pav3loff/logging-app3:latest
