kind: Service
apiVersion: v1
metadata:
  name: logging-app3-service
  namespace: logging
spec:
  selector:
    app: logging-app3
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer

