kind: Service
apiVersion: v1
metadata:
  name: logging-app2-service
  namespace: logging
spec:
  selector:
    app: logging-app2
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer

